@baseUrl = http://localhost:3000


POST http://localhost:3000/api/inventario
Content-Type: application/json

{
    "nome": "Motor Falcon 500",
    "fabricante": "VEX",
    "quantidade_atual": 3,
    "quantidade_min": 2,
    "localizacao": "Bancada B"
}

###

GET http://localhost:3000/api/inventario

###

GET http://localhost:3000/api/inventario/10

###

PUT http://localhost:3000/api/inventario/10
Content-Type: application/json

{
    "nome": "Motor Falcon 500 V2",
    "fabricante": "carro",
    "quantidade_atual": 12,
    "quantidade_min": 2,
    "localizacao": "Bancada B"
}

###

DELETE http://localhost:3000/api/inventario/10

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "admin@inventpro.com",
    "senha": "senhaCriptografada"
}

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Fylipe Denazio",
    "email": "fylipe@inventpro.com",
    "senha": "password123",
    "perfil": "administrador"
}

###

GET http://localhost:3000/produtos

###

POST http://localhost:3000/movimentacoes
Content-Type: application/json

{
    "tipo": "Entrada",
    "quantidade": 15,
    "id_produto": 5
}

